
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/appleboy/gin-jwt"
  version = "2.3.1"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.12.61"

[[constraint]]
  name = "github.com/crewjam/saml"
  version = "0.2.0"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/gin-contrib/location"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.3.0"

[[constraint]]
  name = "github.com/google/go-cmp"
  version = "0.1.0"

[[constraint]]
  name = "github.com/gorilla/context"
  version = "1.1.0"

[[constraint]]
  name = "github.com/gorilla/sessions"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/guregu/dynamo"

[[constraint]]
  branch = "master"
  name = "github.com/juju/loggo"

[[constraint]]
  branch = "master"
  name = "github.com/robbiet480/go.sns"

[[constraint]]
  branch = "master"
  name = "github.com/swaggo/gin-swagger"

[[constraint]]
  name = "github.com/swaggo/swag"
  version = "1.0.0"
